config/routes.rb
Rails.application.routes.draw do
 

  get 'home_page/index'
  
  resources :people 
  resources :tournaments
  resources :golf_courses
  resources :teams
  resources :tournament_organizers
  resources :golf_course_organizers
  root 'home_page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/golf_course.rb
class GolfCourse < ApplicationRecord
end

app/models/golf_course_organizer.rb
class GolfCourseOrganizer < ApplicationRecord
  belongs_to :person
  belongs_to :tournament
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :person
  belongs_to :tournament
end

app/models/registered_team.rb
class RegisteredTeam < ApplicationRecord
  belongs_to :person
  belongs_to :tournament
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  belongs_to :person
  belongs_to :tournament
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :tournament
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :person
end

app/models/tournament.rb
class Tournament < ApplicationRecord
end

app/models/tournament_organizer.rb
class TournamentOrganizer < ApplicationRecord
  belongs_to :person
  belongs_to :tournament
end

app/models/website_admin.rb
class WebsiteAdmin < ApplicationRecord
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/golf_courses_controller.rb
class GolfCoursesController < ApplicationController
  def new
  end
  
  def create
      @golf_course = GolfCourse.new(params.require(:golf_course).permit(:name, :location))
      @golf_course.save
      redirect_to @golf_course
  end
    
  def show
      @golf_course = GolfCourse.find(params[:id])
  end
  
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	def index
		@people = Person.all
	end
	
	def new
	end
	
	def create
		@person = Person.new(person_params)
		@person.save
		redirect_to @person
	end
	
	def show
		@person = Person.find(params[:id])
	end
	
	def edit
		@person = Person.find(params[:id])
	end
	
	def update
		@person = Person.find(params[:id])
		@person.update(person_params)
		redirect_to @person
	end
	
	def destroy
		@person = Person.find(params[:id])
		@person.destroy
		redirect_to people_path
	end
	
	private
		def person_params
			params.require(:person).permit(:firstname, :lastname, :dob, :phone, :location, :email)
		end
	
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
   def index
      @teams = Team.all
   end

   def show 
      @team = Team.find(params[:id])
   end

   def new 
   end
 
   def edit
      @team = Team.find(params[:id])

   end
  
   def create
      @team = Team.new(team_params)
      @team.save
      redirect_to @team
   end

   def update
      @team = Team.find(params[:id])
      @team.update(team_params)
      redirect_to @team
   end
 
   def destroy 
      @team = Team.find(params[:id])
      @team.destroy
      redirect_to teams_path
   end


   private 
      def team_params
         params.require(:team).permit(:name, :tournament_id)
      end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournament_organizers_helper.rb
module TournamentOrganizersHelper
end

app/views/people/edit.html.erb
<h1>Edit your information</h1>

<%= form_for :person, url: person_path(@person), method: :patch do |f| %>

  <p>
    <%= f.label :First_Name %><br>
    <%= f.text_field :firstname %>
  </p>
 
  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :lastname %>
  </p>
  
  <p>
    <%= f.label :Date_of_birth %><br>
    <%= f.text_field :dob %>
  </p>
  
  <p>
    <%= f.label :Address %><br>
    <%= f.text_field :location %>
  </p>
  
  <p>
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone %>
  </p>
  
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', person_path(@person) %> 

app/views/people/index.html.erb
<h1>Registered Users</h1>

<table>
	<tr>
		<th>First name</th>
		<th>Last name</th>
		<th>Email</th>
	</tr>
	
	<% @people.each do |person| %>
		<tr>
			<td><%= person.firstname %></td>
			<td><%= person.lastname %></td>
			<td><%= person.email %></td>
			<td><%= link_to 'Profile', person_path(person) %></td>
			<td><%= link_to 'Delete', person_path(person),
							method: :delete,
							data: {confirm: 'Are you sure?'} %></td>
		</tr>
	<%end%>
</table>
<br>
<%= link_to 'Home', controller: 'home_page' %>

app/views/people/new.html.erb
<h1>Create an account</h1>
<%= form_for :person, url: people_path do |f| %>
  <p>
    <%= f.label :First_Name %><br>
    <%= f.text_field :firstname %>
  </p>
 
  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :lastname %>
  </p>
  
  <p>
    <%= f.label :Date_of_birth %><br>
    <%= f.text_field :dob %>
  </p>
  
  <p>
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone %>
  </p>
  
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', controller: 'home_page' %>

app/views/people/show.html.erb
<%= link_to 'Home', controller: 'home_page' %>

<h1>Profile | <%=@person.firstname%> <%=@person.lastname%></h1>
<br>
<h2>Personal Information</h2>
<p>
    <strong>Date of birth: </strong><%=@person.dob%><br>
	<strong>Address: </strong><%=@person.location%><br>
    <strong>Phone Number: </strong><%=@person.phone%><br>
    <strong>Email: </strong><%=@person.email%><br>
</p>

<%= link_to 'Edit', edit_person_path(@person) %>